#!/usr/bin/env perl

use strict;
use warnings;
use File::Temp qw/ tempfile tempdir /;

my $pacbio_json = `find -L $ENV{TOLQCROOT}/seq/pacbio -mindepth 3 -maxdepth 3 -type d -name reports | smrt2json -m -b $ENV{TOLQCROOT}/data/ -p`;

my ($fh, $filename) = tempfile();
print $fh (qq[
<!DOCTYPE html>
<html lang="en">
    <head>
        <base href="https://tolqc.cog.sanger.ac.uk/">
        <meta charset="utf-8">
        <title>Tree of Life QC: PacBio Report</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.0/cosmo/bootstrap.min.css" media="screen">
        <link rel="stylesheet" href="https://bootswatch.com/_assets/css/custom.min.css">
        <link rel="stylesheet" href="https://unpkg.com/bootstrap-table\@1.18.0/dist/bootstrap-table.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
        <!-- <script src="https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js"></script> -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://unpkg.com/bootstrap-table\@1.18.0/dist/bootstrap-table.min.js"></script>
        <script src="https://bootswatch.com/_assets/js/custom.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.min.js"></script>
    </head>
    <body>
        <div class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
            <div class="container-fluid">
                <a href="/index.html" class="navbar-brand">Tree of Life QC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>


        <div class="container-fluid">
             <div class="page-header" id="banner">
                <div class="row">
                    <div class="col-lg-8 col-md-7 col-sm-6">
                        <h1>PacBio run report</h1>
                    </div>
                </div>
            </div>

            <div class="section" id="pacbio">
                <table id="pacbio_table" style="width: auto"
                    data-pagination="true"
                    data-search="true"
                    data-sort-name="date"
                    data-search-align="left"
                    data-toggle="table"
                    data-show-toggle="true"
                    data-show-columns="true"
                    data-show-columns-toggle-all="true"
                    data-show-export="true"
                    data-sort-order="desc">
                    <thead>
                        <tr>
                            <th data-field="specimen" data-sortable="true">specimen</th>
                            <th data-field="sanger_id" data-sortable="true">sample</th>
                            <th data-field="date" data-sortable="true">date</th>
                            <th data-field="instrument" data-sortable="true">instrument</th>
                            <th data-field="run" data-sortable="true">run</th>
                            <th data-field="movie" data-sortable="true">movie</th>
                            <th data-field="well_label" data-sortable="true">well</th>
                            <!-- <th data-field="sts.MovieLength" data-sortable="true" data-visible="false">movie length</th> -->
                            <th data-field="tag_index" data-sortable="true">tag</th>
                            <th data-field="tag_sequence" data-sortable="true" data-visible="false">tag sequence</th>
                            <th data-field="accession_number" data-sortable="true" data-visible="false">accession</th>
                            <th data-field="library_load_name" data-sortable="true" data-visible="false">library load name</th>
                            <th data-field="sum" data-align='right' data-sortable="true" data-formatter="local_formatter">yield</th>
                            <th data-field="N50" data-align='right' data-sortable="true" data-formatter="local_formatter">N50</th>
                            <th data-field="a" data-align='right' data-sortable="true" data-visible="false">A (&#37;)</th>
                            <th data-field="c" data-align='right' data-sortable="true" data-visible="false">C (&#37;)</th>
                            <th data-field="g" data-align='right' data-sortable="true" data-visible="false">G (&#37;)</th>
                            <th data-field="t" data-align='right' data-sortable="true" data-visible="false">T (&#37;)</th>
                            <th data-field="species_name" data-sortable="true" data-formatter="species_link_formatter">species</th>
                            <th data-field="coi" data-align='right' data-sortable="true" data-sorter="similarity_sorter" data-formatter="bold_topmatch_formatter" data-cell-style="cellStyle">coi</th>
                            <!-- <th data-field="coi" data-align='right' data-sortable="true" data-formatter="bold_modal_formatter">coi</th> -->
                            <!-- CCS report, LIMA report, chemistry, run-stats(P0,P1,P2), run date, instrument, movie-time, pre-ext, seqkit, bindingkit, reagentbox, cell-lot, loading-conc, pass/fail, totalGb, unique molecular yield, polymerase n50, ... -->
                        </tr>
                    </thead>
                </table>
            </div>

            <hr/>

            <div class="footer">
                    <a href="https://www.sanger.ac.uk/"><img style="float:right; height:50px" src="https://imputation.sanger.ac.uk/www/images/sanger_logo.png" class="img-responsive" alt="WTSI"></a>
                    <p class="copyright">Tree of Life Species Report is developed within the <a href="https://www.sanger.ac.uk/programme/tree-of-life/">Tree of Life Programme</a>
                    at the <a href="https://www.sanger.ac.uk/">Wellcome Sanger Institute</a><br />
                    Copyright &copy; 2020 Genome Research Limited (reg no. 2742969) is a charity registered in England with number 1021457.<br />
                    <a href="http://www.sanger.ac.uk/legal/">Terms and conditions</a> | <a href="http://www.sanger.ac.uk/legal/cookiespolicy.html">Cookies policy</a>.
            </div>
        </div>

        <script type="text/javascript">

        \$(document).on('click', '[data-toggle="lightbox"]', function(event) {
            event.preventDefault();
            \$(this).ekkoLightbox();
        });

        function similarity_sorter(a, b, rowA, rowB) {
            var aa = (rowA.match && rowA.species_name && rowA.match[0].similarity && rowA.match[0].taxonomicidentification) ? rowA.match[0].similarity : 0.0;
            var bb = (rowB.match && rowB.species_name && rowB.match[0].similarity && rowB.match[0].taxonomicidentification) ? rowB.match[0].similarity : 0.0;
            if (aa>0) {
                var speciesA = rowA.species_name;
                var taxA = rowA.match[0].taxonomicidentification;
                if (!speciesA.startsWith(taxA) && !taxA.startsWith(speciesA)) { aa = -aa; }
            }
            if (bb>0) {
                var speciesB = rowB.species_name;
                var taxB = rowB.match[0].taxonomicidentification;
                if (!speciesB.startsWith(taxB) && !taxB.startsWith(speciesB)) { bb = -bb; }
            }
            if (aa<bb) { return -1; }
            else if (aa>bb) { return 1; }
            else { return  0; }
        }
        function bold_url_formatter(value, row, index) {
            return '<a href="'+row.specimen.url+'">'+value+'</a>';
        }
        function cellStyle(value, row, index) {
            if (row.match && row.species_name)
            {
                var species_lims = row.species_name;
                var taxonomicidentification = row.match[0].taxonomicidentification;
                if (!species_lims.startsWith(taxonomicidentification) && !taxonomicidentification.startsWith(species_lims)) {
                    return {
                        classes: 'bg-danger'
                    }
                } else if (parseFloat(row.match[0].similarity) < 0.97) {
                    return {
                        classes: 'bg-warning'
                    }
                } else {
                    return {
                        classes: 'bg-success'
                    }
                }
            } else {
                return {
                    classes: 'bg-warning'
                }
            }
        }
        function bold_topmatch_formatter(value, row) {
            if (row.match && row.species_name)
            {
                var species_lims = row.species_name;
                var taxonomicidentification = row.match[0].taxonomicidentification;
                if (!species_lims.startsWith(taxonomicidentification) && !taxonomicidentification.startsWith(species_lims)) {
                    return '<i>'+row.match[0].taxonomicidentification+'</i> ('+parseFloat(row.match[0].similarity).toFixed(2)+')';
                } else if (parseFloat(row.match[0].similarity) < 0.97) {
                    return '<i>'+row.match[0].taxonomicidentification+'</i> ('+parseFloat(row.match[0].similarity).toFixed(2)+')';
                } else {
                    return '<i>'+row.match[0].taxonomicidentification+'</i> ('+parseFloat(row.match[0].similarity).toFixed(2)+')';
                }
            } else {
                return '-';
            }
        }
        function taxon_link_formatter(value, row) {
            return '<a href="https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id='+value+'">'+value+'</a>';
        }
        function species_link_formatter(value, row) {
            if (value) {
                var _name = value.replace(/ /g, "_");
                return '<i><a href="'+row.group+'/'+_name+'/index.html">'+value+'</a></i>';
            } else {
                return value;
            }
        }
        function illumina_image_formatter(index, row) {
            var illumina_plots = '';
            var x;
            for (x in row) {
                if (x.match(/^plot/)) {
                    var img = encodeURIComponent(row[x]);
                    illumina_plots += '<a href="'+img+'" data-toggle="lightbox" data-title="'+row.type+' '+row.specimen+' samtools stats plots" data-toggle="lightbox" data-gallery="illumina'+index+'"><img src="'+img+'" height="75px"></a>';
                }
            }
            return illumina_plots;
        }
        function local_formatter(value) {
            return value.toLocaleString();
        }
        function dec2_formatter(value) {
            return parseFloat(value).toFixed(2);
        }
        function info_formatter(value) {
            return '<strong>' + value + '</strong>';
        }

        var pacbio = $pacbio_json;
        \$('#pacbio_table').bootstrapTable({data: pacbio});

        </script>
    </body>
</html>
]);
close($fh);

system(qq[s3cmd --quiet put $filename s3://tolqc/pacbio.html && s3cmd --quiet setacl --acl-public s3://tolqc/pacbio.html]);

exit;
